export const DEFAULT_A11Y_CONFIG = {
  fontSize: 'normal', // 'normal' | 'large' | 'xlarge'
  dyslexicFont: false,
  lineSpacing: 'normal', // 'normal' | 'increased'
  highContrast: false,
  reducedMotion: false,
  simplifiedLanguage: false,
  language: 'en', // 'en' | 'es' | 'fr' | 'de' | 'hi' | 'ja' | 'zh'
  ttsSpeed: 1.0, // 0.8 | 1.0 | 1.25 | 1.5
};

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', nativeName: 'English' },
  { code: 'es', label: 'Spanish', nativeName: 'Español' },
  { code: 'fr', label: 'French', nativeName: 'Français' },
  { code: 'de', label: 'German', nativeName: 'Deutsch' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ja', label: 'Japanese', nativeName: '日本語' },
  { code: 'zh', label: 'Chinese', nativeName: '中文' },
];

export const UI_TRANSLATIONS = {
  en: {
    skipToMain: 'Skip to main content',
    a11ySettings: 'Accessibility Settings',
    devSettings: 'Dev Settings',
    home: 'Home',
    uploadTitle: 'Upload Document / Image',
    pasteTitle: 'Paste Text',
    dropzoneText: 'Drop PDF or Image document here to analyze',
    dropzoneHint: 'Supports PDF, PNG, JPG, WEBP (Image Recognition OCR)',
    pastePlaceholder: 'Paste contract or agreement text here...',
    analyzeText: 'Analyze Document Text',
    sampleNDA: 'Sample NDA',
    sampleLease: 'Sample Lease',
    analysisTab: 'Analysis',
    qaTab: 'Q&A',
    exportReport: 'Export Report',
    readAloud: 'Read Aloud',
    stopReading: 'Stop Reading',
    pauseReading: 'Pause',
    resumeReading: 'Resume',
    fontSize: 'Font Size',
    dyslexicFont: 'Dyslexia-Friendly Font',
    lineSpacing: 'Line & Text Spacing',
    highContrast: 'High Contrast Mode',
    reducedMotion: 'Reduced Motion',
    simplifiedLang: 'Simplify Legal Terminology (Plain English)',
    uiLanguage: 'Language',
    speechSpeed: 'Reading Speed',
    close: 'Close',
    save: 'Save Preferences',
    highRisk: 'High Risk',
    mediumRisk: 'Moderate Risk',
    lowRisk: 'Low Risk / Standard',
  },
  es: {
    skipToMain: 'Saltar al contenido principal',
    a11ySettings: 'Configuración de accesibilidad',
    devSettings: 'Ajustes de desarrollo',
    home: 'Inicio',
    uploadTitle: 'Subir documento / Imagen',
    pasteTitle: 'Pegar texto',
    dropzoneText: 'Suelte el documento PDF o imagen aquí para analizar',
    dropzoneHint: 'Soporta PDF, PNG, JPG, WEBP (OCR)',
    pastePlaceholder: 'Pegue el texto del contrato o acuerdo aquí...',
    analyzeText: 'Analizar texto del documento',
    sampleNDA: 'NDA de muestra',
    sampleLease: 'Arrendamiento de muestra',
    analysisTab: 'Análisis',
    qaTab: 'Preguntas y Respuestas',
    exportReport: 'Exportar informe',
    readAloud: 'Leer en voz alta',
    stopReading: 'Detener lectura',
    pauseReading: 'Pausar',
    resumeReading: 'Continuar',
    fontSize: 'Tamaño de fuente',
    dyslexicFont: 'Fuente para dislexia',
    lineSpacing: 'Interlineado',
    highContrast: 'Modo alto contraste',
    reducedMotion: 'Movimiento reducido',
    simplifiedLang: 'Simplificar lenguaje legal',
    uiLanguage: 'Idioma',
    speechSpeed: 'Velocidad de lectura',
    close: 'Cerrar',
    save: 'Guardar preferencias',
    highRisk: 'Riesgo Alto',
    mediumRisk: 'Riesgo Moderado',
    lowRisk: 'Bajo Riesgo',
  },
  fr: {
    skipToMain: 'Aller au contenu principal',
    a11ySettings: 'Paramètres d’accessibilité',
    devSettings: 'Options développeur',
    home: 'Accueil',
    uploadTitle: 'Téléverser document / Image',
    pasteTitle: 'Coller du texte',
    dropzoneText: 'Déposez votre document PDF ou image ici',
    dropzoneHint: 'Prend en charge PDF, PNG, JPG, WEBP (OCR)',
    pastePlaceholder: 'Collez le texte de votre contrat ici...',
    analyzeText: 'Analyser le texte',
    sampleNDA: 'Exemple NDA',
    sampleLease: 'Exemple Bail',
    analysisTab: 'Analyse',
    qaTab: 'Questions / Réponses',
    exportReport: 'Exporter le rapport',
    readAloud: 'Lecture vocale',
    stopReading: 'Arrêter la lecture',
    pauseReading: 'Pause',
    resumeReading: 'Reprendre',
    fontSize: 'Taille du texte',
    dyslexicFont: 'Police adaptée à la dyslexie',
    lineSpacing: 'Espacement du texte',
    highContrast: 'Mode Contraste Élevé',
    reducedMotion: 'Mouvement réduit',
    simplifiedLang: 'Simplifier le langage juridique',
    uiLanguage: 'Langue',
    speechSpeed: 'Vitesse de lecture',
    close: 'Fermer',
    save: 'Enregistrer',
    highRisk: 'Risque Élevé',
    mediumRisk: 'Risque Modéré',
    lowRisk: 'Faible Risque',
  },
  de: {
    skipToMain: 'Zum Hauptinhalt springen',
    a11ySettings: 'Barrierefreiheit-Einstellungen',
    devSettings: 'Entwickler-Einstellungen',
    home: 'Startseite',
    uploadTitle: 'Dokument / Bild hochladen',
    pasteTitle: 'Text einfügen',
    dropzoneText: 'PDF oder Bild hierher ziehen zum Analysieren',
    dropzoneHint: 'Unterstützt PDF, PNG, JPG, WEBP (OCR)',
    pastePlaceholder: 'Vertragstext hier einfügen...',
    analyzeText: 'Dokumententext analysieren',
    sampleNDA: 'Beispiel-NDA',
    sampleLease: 'Beispiel-Mietvertrag',
    analysisTab: 'Analyse',
    qaTab: 'Fragen & Antworten',
    exportReport: 'Bericht exportieren',
    readAloud: 'Vorlesen',
    stopReading: 'Stoppen',
    pauseReading: 'Pause',
    resumeReading: 'Fortsetzen',
    fontSize: 'Schriftgröße',
    dyslexicFont: 'Legasthenie-Schriftart',
    lineSpacing: 'Zeilenabstand',
    highContrast: 'Hoher Kontrast',
    reducedMotion: 'Reduzierte Bewegung',
    simplifiedLang: 'Rechtssprache vereinfachen',
    uiLanguage: 'Sprache',
    speechSpeed: 'Lesegeschwindigkeit',
    close: 'Schließen',
    save: 'Einstellungen speichern',
    highRisk: 'Hohes Risiko',
    mediumRisk: 'Mittleres Risiko',
    lowRisk: 'Geringes Risiko',
  },
  hi: {
    skipToMain: 'मुख्य सामग्री पर जाएँ',
    a11ySettings: 'सुगम्यता (Accessibility) सेटिंग्स',
    devSettings: 'डेवलपर सेटिंग्स',
    home: 'होम',
    uploadTitle: 'दस्तावेज़ / चित्र अपलोड करें',
    pasteTitle: 'पाठ (Text) पेस्ट करें',
    dropzoneText: 'विश्लेषण के लिए पीडीएफ या छवि यहाँ डालें',
    dropzoneHint: 'PDF, PNG, JPG, WEBP (OCR) समर्थित',
    pastePlaceholder: 'अनुबंध का पाठ यहाँ पेस्ट करें...',
    analyzeText: 'दस्तावेज़ पाठ का विश्लेषण करें',
    sampleNDA: 'नमूना NDA',
    sampleLease: 'नमूना लीज',
    analysisTab: 'विश्लेषण',
    qaTab: 'प्रश्न और उत्तर',
    exportReport: 'रिपोर्ट डाउनलोड करें',
    readAloud: 'बोलकर सुनें',
    stopReading: 'पठन रोकें',
    pauseReading: 'विराम',
    resumeReading: 'पुनः प्रारंभ',
    fontSize: 'फ़ॉन्ट आकार',
    dyslexicFont: 'डिस्लेक्सिया-अनुकूल फ़ॉन्ट',
    lineSpacing: 'पंक्ति रिक्ति (Line Spacing)',
    highContrast: 'उच्च कंट्रास्ट मोड',
    reducedMotion: 'कम गति (Reduced Motion)',
    simplifiedLang: 'सरल भाषा मोड',
    uiLanguage: 'भाषा',
    speechSpeed: 'पढ़ने की गति',
    close: 'बंद करें',
    save: 'सहेजें',
    highRisk: 'उच्च जोखिम',
    mediumRisk: 'मध्यम जोखिम',
    lowRisk: 'कम जोखिम',
  },
  ja: {
    skipToMain: 'メインコンテンツへスキップ',
    a11ySettings: 'アクセシビリティ設定',
    devSettings: '開発者設定',
    home: 'ホーム',
    uploadTitle: '文書/画像をアップロード',
    pasteTitle: 'テキストを貼り付け',
    dropzoneText: 'PDFまたは画像ドキュメントをドラッグ＆ドロップ',
    dropzoneHint: 'PDF、PNG、JPG、WEBP（OCR対応）',
    pastePlaceholder: '契約テキストをここに貼り付けてください...',
    analyzeText: '文書テキストを解析',
    sampleNDA: 'サンプル秘密保持契約',
    sampleLease: 'サンプル賃貸契約',
    analysisTab: '分析',
    qaTab: '質疑応答',
    exportReport: 'レポートをエクスポート',
    readAloud: '音声読み上げ',
    stopReading: '停止',
    pauseReading: '一時停止',
    resumeReading: '再開',
    fontSize: 'フォントサイズ',
    dyslexicFont: '失読症配慮フォント',
    lineSpacing: '行間設定',
    highContrast: 'ハイコントラストモード',
    reducedMotion: '視覚効果を軽減',
    simplifiedLang: '専門用語の平易化',
    uiLanguage: '言語',
    speechSpeed: '読み上げ速度',
    close: '閉じる',
    save: '設定を保存',
    highRisk: '高リスク',
    mediumRisk: '中リスク',
    lowRisk: '低リスク',
  },
  zh: {
    skipToMain: '跳转至主要内容',
    a11ySettings: '无障碍设置',
    devSettings: '开发者设置',
    home: '首页',
    uploadTitle: '上传文档 / 图片',
    pasteTitle: '粘贴文本',
    dropzoneText: '拖拽 PDF 或图片文件至此处解析',
    dropzoneHint: '支持 PDF、PNG、JPG、WEBP (OCR)',
    pastePlaceholder: '在此处粘贴合同或协议文本...',
    analyzeText: '分析文档文本',
    sampleNDA: '示例保密协议',
    sampleLease: '示例租赁合同',
    analysisTab: '分析结果',
    qaTab: '问答助手',
    exportReport: '导出分析报告',
    readAloud: '朗读文本',
    stopReading: '停止朗读',
    pauseReading: '暂停',
    resumeReading: '继续',
    fontSize: '字体大小',
    dyslexicFont: '读写障碍友好字体',
    lineSpacing: '行距设置',
    highContrast: '高对比度模式',
    reducedMotion: '减少动画效果',
    simplifiedLang: '简化法律术语（通俗易懂）',
    uiLanguage: '界面语言',
    speechSpeed: '语速设置',
    close: '关闭',
    save: '保存偏好',
    highRisk: '高风险',
    mediumRisk: '中等风险',
    lowRisk: '低风险',
  }
};
