import { useState, useEffect } from 'react';
import { generateLawyerPrepBrief } from '../services/aiService';
import AudioReader from './AudioReader';

export default function LawyerPrep({ documentText, apiConfig, a11yConfig = {} }) {
  const [prepData, setPrepData] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (!documentText || !apiConfig || !apiConfig.apiKey) return;

    let isMounted = true;
    setIsLoading(true);

    generateLawyerPrepBrief(documentText, apiConfig, a11yConfig)
      .then((raw) => {
        if (!isMounted) return;
        try {
          const match = raw.match(/\{[\s\S]*\}/);
          if (match) {
            setPrepData(JSON.parse(match[0]));
          }
        } catch {
          setPrepData(null);
        }
      })
      .catch((err) => {
        console.error(err);
      })
      .finally(() => {
        if (isMounted) setIsLoading(false);
      });

    return () => {
      isMounted = false;
    };
  }, [documentText, apiConfig, a11yConfig]);

  const handleExportBrief = () => {
    if (!prepData) return;
    let text = `# Attorney Consultation Brief\n\n`;
    text += `## Document Overview\n${prepData.document_summary_brief || ''}\n\n`;

    if (prepData.high_priority_concerns?.length) {
      text += `## High Priority Review Items for Lawyer\n`;
      prepData.high_priority_concerns.forEach((item, i) => {
        text += `${i + 1}. ${item}\n`;
      });
      text += `\n`;
    }

    if (prepData.questions_for_lawyer?.length) {
      text += `## Specific Questions to Ask Your Lawyer\n`;
      prepData.questions_for_lawyer.forEach((q, i) => {
        text += `${i + 1}. ${q}\n`;
      });
      text += `\n`;
    }

    if (prepData.recommended_negotiations?.length) {
      text += `## Recommended Terms to Negotiate\n`;
      prepData.recommended_negotiations.forEach((n, i) => {
        text += `${i + 1}. ${n}\n`;
      });
      text += `\n`;
    }

    text += `---\n*Generated by Lexora - AI Legal Document Assistant (For Informational Use)*\n`;

    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    try {
      const a = document.createElement('a');
      a.href = url;
      a.download = `Attorney-Consultation-Brief.md`;
      a.click();
    } finally {
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    }
  };

  if (isLoading) {
    return (
      <div className="lawyer-prep-container loading" role="status" aria-live="polite">
        <p className="lawyer-prep-loading-text">Preparing Attorney Consultation Brief...</p>
      </div>
    );
  }

  if (!prepData) {
    return (
      <div className="lawyer-prep-container empty">
        <h3>Attorney Consultation Readiness Tool</h3>
        <p>Upload a legal document to generate a consultation brief and specific questions to ask an attorney.</p>
      </div>
    );
  }

  const spokenBriefText = `
    Attorney Consultation Brief.
    ${prepData.document_summary_brief || ''}.
    ${prepData.questions_for_lawyer ? prepData.questions_for_lawyer.length + ' questions prepared for your lawyer.' : ''}
  `;

  return (
    <div className="lawyer-prep-container" role="region" aria-label="Lawyer Consultation Readiness Tool">
      <div className="lawyer-prep-header">
        <div>
          <h2>Attorney Consultation Readiness Brief</h2>
          <p>Prepare key questions and review points to bring to a professional legal consultation.</p>
        </div>
        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
          <AudioReader
            text={spokenBriefText}
            label="Attorney Consultation Brief"
            lang={a11yConfig.language || 'en'}
            rate={a11yConfig.ttsSpeed || 1.0}
          />
          <button type="button" className="export-btn" onClick={handleExportBrief}>
            📥 Export Brief for Lawyer
          </button>
        </div>
      </div>

      <div className="brief-card summary-brief">
        <h3>📋 Executive Brief</h3>
        <p>{prepData.document_summary_brief}</p>
      </div>

      <div className="brief-grid">
        {/* Specific Questions for Lawyer */}
        {prepData.questions_for_lawyer && prepData.questions_for_lawyer.length > 0 && (
          <div className="brief-card questions-card">
            <h3>❓ 5-7 Questions to Ask Your Lawyer</h3>
            <ol className="brief-list">
              {prepData.questions_for_lawyer.map((q, idx) => (
                <li key={idx}>{q}</li>
              ))}
            </ol>
          </div>
        )}

        {/* High Priority Concerns */}
        {prepData.high_priority_concerns && prepData.high_priority_concerns.length > 0 && (
          <div className="brief-card concerns-card">
            <h3>🚨 High Priority Items for Lawyer Review</h3>
            <ul className="brief-list">
              {prepData.high_priority_concerns.map((item, idx) => (
                <li key={idx}>{item}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Recommended Terms to Negotiate */}
        {prepData.recommended_negotiations && prepData.recommended_negotiations.length > 0 && (
          <div className="brief-card negotiations-card">
            <h3>⚖️ Terms Recommended to Negotiate</h3>
            <ul className="brief-list">
              {prepData.recommended_negotiations.map((item, idx) => (
                <li key={idx}>{item}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}
